// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>XMlShredder</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace XCabBookingFileExtractor.CapitalSchemaV2
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    #region Base entity class
    public partial class EntityBase<T>
    {

        private static System.Xml.Serialization.XmlSerializer serializer;

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
                }
                return serializer;
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current EntityBase object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize()
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes workflow markup into an EntityBase object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out T obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static T Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current EntityBase object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual void SaveToFile(string fileName)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an EntityBase object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out T obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static T LoadFromFile(string fileName)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion
    }
    #endregion

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Requests : EntityBase<Requests>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<Request> requestField;

        /// <summary>
        /// Requests class constructor
        /// </summary>
        public Requests()
        {
            this.requestField = new List<Request>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Request", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<Request> Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class Request : EntityBase<Request>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private RequestBookingType bookingTypeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private LocationType fromDetailField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private RequestToLegs toLegsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string accountCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string callerField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string driverNumberField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string runCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string serviceCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime earliestField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool earliestFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime latestField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool latestFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime plannedField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool plannedFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private CapBusiness capitalStateField;

        /// <summary>
        /// Request class constructor
        /// </summary>
        public Request()
        {
            this.toLegsField = new RequestToLegs();
            this.fromDetailField = new LocationType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestBookingType BookingType
        {
            get
            {
                return this.bookingTypeField;
            }
            set
            {
                this.bookingTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LocationType FromDetail
        {
            get
            {
                return this.fromDetailField;
            }
            set
            {
                this.fromDetailField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestToLegs ToLegs
        {
            get
            {
                return this.toLegsField;
            }
            set
            {
                this.toLegsField = value;
            }
        }

        /// <summary>
        /// Your account code will be provided to you by your Capital Transport representative
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccountCode
        {
            get
            {
                return this.accountCodeField;
            }
            set
            {
                this.accountCodeField = value;
            }
        }

        /// <summary>
        /// Caller Field, could be used to provide the run code
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Caller
        {
            get
            {
                return this.callerField;
            }
            set
            {
                this.callerField = value;
            }
        }
        /// <summary>
        /// Driver Number
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DriverNumber
        {
            get
            {
                return this.driverNumberField;
            }
            set
            {
                this.driverNumberField = value;
            }
        }
        /// <summary>
        /// RunCode Field
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RunCode
        {
            get
            {
                return this.runCodeField;
            }
            set
            {
                this.runCodeField = value;
            }
        }

        /// <summary>
        /// Service Code under which the jobs will be booked
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }

        /// <summary>
        /// Earliest Date Time will indicate the earliest time when the job can be picked. The field follows ISO 8601 standard, we typically use: yyyy-MM-dd
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Earliest
        {
            get
            {
                return this.earliestField;
            }
            set
            {
                this.earliestField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarliestSpecified
        {
            get
            {
                return this.earliestFieldSpecified;
            }
            set
            {
                this.earliestFieldSpecified = value;
            }
        }

        /// <summary>
        /// Latest Date Time will indicate the latest time when the job can be picked. The field follows ISO 8601 standard, we typically use: yyyy-MM-dd
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Latest
        {
            get
            {
                return this.latestField;
            }
            set
            {
                this.latestField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestSpecified
        {
            get
            {
                return this.latestFieldSpecified;
            }
            set
            {
                this.latestFieldSpecified = value;
            }
        }

        /// <summary>
        /// Planned Date Time will indicate the planned time when the job is preferred to be picked up. The field follows ISO 8601 standard, we typically use: yyyy-MM-dd
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Planned
        {
            get
            {
                return this.plannedField;
            }
            set
            {
                this.plannedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedSpecified
        {
            get
            {
                return this.plannedFieldSpecified;
            }
            set
            {
                this.plannedFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapBusiness CapitalState
        {
            get
            {
                return this.capitalStateField;
            }
            set
            {
                this.capitalStateField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum RequestBookingType
    {

        /// <remarks/>
        BOOKING,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class LocationType : EntityBase<LocationType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locSuburbField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locPostcodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locDetail1Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locDetail2Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locDetail3Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locDetail4Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locDetail5Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string locNotesField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string specialInstructionsField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locSuburb
        {
            get
            {
                return this.locSuburbField;
            }
            set
            {
                this.locSuburbField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger")]
        public string locPostcode
        {
            get
            {
                return this.locPostcodeField;
            }
            set
            {
                this.locPostcodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locDetail1
        {
            get
            {
                return this.locDetail1Field;
            }
            set
            {
                this.locDetail1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locDetail2
        {
            get
            {
                return this.locDetail2Field;
            }
            set
            {
                this.locDetail2Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locDetail3
        {
            get
            {
                return this.locDetail3Field;
            }
            set
            {
                this.locDetail3Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locDetail4
        {
            get
            {
                return this.locDetail4Field;
            }
            set
            {
                this.locDetail4Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locDetail5
        {
            get
            {
                return this.locDetail5Field;
            }
            set
            {
                this.locDetail5Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locNotes
        {
            get
            {
                return this.locNotesField;
            }
            set
            {
                this.locNotesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SpecialInstructions
        {
            get
            {
                return this.specialInstructionsField;
            }
            set
            {
                this.specialInstructionsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class PhoneNumberType : EntityBase<PhoneNumberType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string areaCodeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string phoneNumberField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string descriptionField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AreaCode
        {
            get
            {
                return this.areaCodeField;
            }
            set
            {
                this.areaCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class itemType : EntityBase<itemType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string itmDescriptionField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal itmLengthField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool itmLengthFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal itmWidthField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool itmWidthFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal itmHeightField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool itmHeightFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal itmWeightField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool itmWeightFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private decimal itmCubicField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool itmCubicFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string itmBarcodeField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string itmDescription
        {
            get
            {
                return this.itmDescriptionField;
            }
            set
            {
                this.itmDescriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal itmLength
        {
            get
            {
                return this.itmLengthField;
            }
            set
            {
                this.itmLengthField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itmLengthSpecified
        {
            get
            {
                return this.itmLengthFieldSpecified;
            }
            set
            {
                this.itmLengthFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal itmWidth
        {
            get
            {
                return this.itmWidthField;
            }
            set
            {
                this.itmWidthField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itmWidthSpecified
        {
            get
            {
                return this.itmWidthFieldSpecified;
            }
            set
            {
                this.itmWidthFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal itmHeight
        {
            get
            {
                return this.itmHeightField;
            }
            set
            {
                this.itmHeightField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itmHeightSpecified
        {
            get
            {
                return this.itmHeightFieldSpecified;
            }
            set
            {
                this.itmHeightFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal itmWeight
        {
            get
            {
                return this.itmWeightField;
            }
            set
            {
                this.itmWeightField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itmWeightSpecified
        {
            get
            {
                return this.itmWeightFieldSpecified;
            }
            set
            {
                this.itmWeightFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal itmCubic
        {
            get
            {
                return this.itmCubicField;
            }
            set
            {
                this.itmCubicField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itmCubicSpecified
        {
            get
            {
                return this.itmCubicFieldSpecified;
            }
            set
            {
                this.itmCubicFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string itmBarcode
        {
            get
            {
                return this.itmBarcodeField;
            }
            set
            {
                this.itmBarcodeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RequestToLegs : EntityBase<RequestToLegs>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private RequestToLegsLeg legField;

        /// <summary>
        /// RequestToLegs class constructor
        /// </summary>
        public RequestToLegs()
        {
            this.legField = new RequestToLegsLeg();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestToLegsLeg Leg
        {
            get
            {
                return this.legField;
            }
            set
            {
                this.legField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RequestToLegsLeg : EntityBase<RequestToLegsLeg>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string ref1Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string ref2Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string ref3Field;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string trackAndTraceSmsNumberField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string trackAndTraceEmailAddressField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private LocationType toDetailField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<itemType> itemsField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<PhoneNumberType> phoneNumbersField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime earliestField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool earliestFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime latestField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool latestFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private System.DateTime plannedField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool plannedFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string atlField;

        /// <summary>
        /// RequestToLegsLeg class constructor
        /// </summary>
        public RequestToLegsLeg()
        {
            this.phoneNumbersField = new List<PhoneNumberType>();
            this.itemsField = new List<itemType>();
            this.toDetailField = new LocationType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ref1
        {
            get
            {
                return this.ref1Field;
            }
            set
            {
                this.ref1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ref2
        {
            get
            {
                return this.ref2Field;
            }
            set
            {
                this.ref2Field = value;
            }
        }

        /// <summary>
        /// Provide an additional reference only applicable to specific clients
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string Ref3
        {
            get
            {
                return this.ref3Field;
            }
            set
            {
                this.ref3Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TrackAndTraceSmsNumber
        {
            get
            {
                return this.trackAndTraceSmsNumberField;
            }
            set
            {
                this.trackAndTraceSmsNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string TrackAndTraceEmailAddress
        {
            get
            {
                return this.trackAndTraceEmailAddressField;
            }
            set
            {
                this.trackAndTraceEmailAddressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string ATL
        {
            get
            {
                return this.atlField;
            }
            set
            {
                this.atlField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LocationType ToDetail
        {
            get
            {
                return this.toDetailField;
            }
            set
            {
                this.toDetailField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<itemType> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PhoneNumber", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<PhoneNumberType> PhoneNumbers
        {
            get
            {
                return this.phoneNumbersField;
            }
            set
            {
                this.phoneNumbersField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Earliest
        {
            get
            {
                return this.earliestField;
            }
            set
            {
                this.earliestField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarliestSpecified
        {
            get
            {
                return this.earliestFieldSpecified;
            }
            set
            {
                this.earliestFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Latest
        {
            get
            {
                return this.latestField;
            }
            set
            {
                this.latestField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestSpecified
        {
            get
            {
                return this.latestFieldSpecified;
            }
            set
            {
                this.latestFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Planned
        {
            get
            {
                return this.plannedField;
            }
            set
            {
                this.plannedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedSpecified
        {
            get
            {
                return this.plannedFieldSpecified;
            }
            set
            {
                this.plannedFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum CapBusiness
    {

        /// <remarks/>
        VIC,

        /// <remarks/>
        WA,

        /// <remarks/>
        SA,

        /// <remarks/>
        NSW,

        /// <remarks/>
        QLD,

        /// <remarks/>
        ACT,
    }
}
