//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    public sealed partial class DbSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DbSettings defaultInstance = ((DbSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DbSettings())));
        
        public static DbSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ApplicationSql.challengelogistics.com.au;Initial Catalog=xcab;Persist" +
            " Security Info=true;User ID=ccr_user; Password = ccr1234;TrustServerCertificate=" +
            "True;")]
        public string ApplicationSqlDatabaseConnectionString {
            get {
                return ((string)(this["ApplicationSqlDatabaseConnectionString"]));
            }
            set {
                this["ApplicationSqlDatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=ilogixdbserver;Pooling=true;Uid=iLogixDev;Pwd=ilogix256;Database=ilogixdb;" +
            "Connection Timeout=15;charset=utf8;")]
        public string ILogixMysqlConnection {
            get {
                return ((string)(this["ILogixMysqlConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software-Development@capitaltransport.com.au")]
        public string EmailRecipientList {
            get {
                return ((string)(this["EmailRecipientList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendTrackEventNotification {
            get {
                return ((bool)(this["SendTrackEventNotification"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp\\xCab")]
        public string LocalDownloadFolder {
            get {
                return ((string)(this["LocalDownloadFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bookings")]
        public string FolderNameBookings {
            get {
                return ((string)(this["FolderNameBookings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tracking")]
        public string FolderNameTracking {
            get {
                return ((string)(this["FolderNameTracking"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Processed")]
        public string ProcessedFolderName {
            get {
                return ((string)(this["ProcessedFolderName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error_Files")]
        public string ErrorFolderName {
            get {
                return ((string)(this["ErrorFolderName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://192.168.160.15")]
        public string TyphonFtpConnectionString {
            get {
                return ((string)(this["TyphonFtpConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xml")]
        public string BookingFileExtension {
            get {
                return ((string)(this["BookingFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("edi")]
        public string EdiFactExtension {
            get {
                return ((string)(this["EdiFactExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ReportSql.challengelogistics.com.au;Initial Catalog=Tplus;Persist Sec" +
            "urity Info=true;User ID=xcab_user; Password = xcab1234;TrustServerCertificate=Tr" +
            "ue;")]
        public string SecondaryDbConnectionString {
            get {
                return ((string)(this["SecondaryDbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source =\r\n  (DESCRIPTION =\r\n    (ADDRESS_LIST =\r\n      (ADDRESS = (PROTOCOL " +
            "= TCP)(HOST = tplusmeldb)(PORT = 1521))\r\n    )\r\n    (CONNECT_DATA =\r\n      (SERV" +
            "ICE_NAME = TPLUS)\r\n    )\r\n  );\r\nUser Id=tplus_user;password=iam34;")]
        public string TplusMELDatabaseConnectionString {
            get {
                return ((string)(this["TplusMELDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source =\r\n  (DESCRIPTION =\r\n    (ADDRESS_LIST =\r\n      (ADDRESS = (PROTOCOL " +
            "= TCP)(HOST = tplusbnedb)(PORT = 1521))\r\n    )\r\n    (CONNECT_DATA =\r\n      (SERV" +
            "ICE_NAME = TPLUS)\r\n    )\r\n  );\r\nUser Id=tplus_user;password=iam34;")]
        public string TplusBNEDatabaseConnectionString {
            get {
                return ((string)(this["TplusBNEDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = \r\n (DESCRIPTION =\r\n    (ADDRESS_LIST =\r\n      (ADDRESS = (PROTOCOL " +
            "= TCP)(HOST = tplusperdb)(PORT = 1521))\r\n    )\r\n    (CONNECT_DATA =\r\n      (SERV" +
            "ICE_NAME = TPLUS)\r\n    )\r\n  );\r\nUser Id=tplus_user;password=iam34;")]
        public string TplusPERDatabaseConnectionString {
            get {
                return ((string)(this["TplusPERDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source =\r\n  (DESCRIPTION =\r\n    (ADDRESS_LIST =\r\n      (ADDRESS = (PROTOCOL " +
            "= TCP)(HOST = tplusadldb)(PORT = 1521))\r\n    )\r\n    (CONNECT_DATA =\r\n      (SERV" +
            "ICE_NAME = TPLUS)\r\n    )\r\n  );\r\nUser Id=tplus_user;password=iam34;")]
        public string TplusADLDatabaseConnectionString {
            get {
                return ((string)(this["TplusADLDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source =\r\n  (DESCRIPTION =\r\n    (ADDRESS_LIST =\r\n      (ADDRESS = (PROTOCOL " +
            "= TCP)(HOST = tplussyddb)(PORT = 1521))\r\n    )\r\n    (CONNECT_DATA =\r\n      (SERV" +
            "ICE_NAME = TPLUS)\r\n    )\r\n  );\r\nUser Id=tplus_user;password=iam34;")]
        public string TplusSYDDatabaseConnectionString {
            get {
                return ((string)(this["TplusSYDDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=p1-ntx-ixarch01.challengelogistics.com.au;Pooling=true;Uid=iLogixDev;Pwd=i" +
            "logix256;Database=ilogixdb;Connection Timeout=30;")]
        public string ILogixArchivedDbConnectionString {
            get {
                return ((string)(this["ILogixArchivedDbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=devsql.challengelogistics.com.au;Initial Catalog=xcab;Persist Securit" +
            "y Info=true;User ID=xcab_user; Password = xcab1234;TrustServerCertificate=True;")]
        public string XCabDevDatabase {
            get {
                return ((string)(this["XCabDevDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POD")]
        public string LocalPODFolderName {
            get {
                return ((string)(this["LocalPODFolderName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseComo {
            get {
                return ((bool)(this["UseComo"]));
            }
            set {
                this["UseComo"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=ilogixdbserver.challengelogistics.com.au;Pooling=true;Uid=iLogixWebProApp;" +
            "Pwd=ilogix256;Database=ilogixdb;Connection Timeout=30;")]
        public string ILogixWebProAppConnectionString {
            get {
                return ((string)(this["ILogixWebProAppConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ReportSql.challengelogistics.com.au;Initial Catalog=TPlus;Persist Sec" +
            "urity Info=true;User ID=xcab_user; Password = xcab1234;TrustServerCertificate=Tr" +
            "ue;")]
        public string ReportSqlDatabaseConnectionString {
            get {
                return ((string)(this["ReportSqlDatabaseConnectionString"]));
            }
            set {
                this["ReportSqlDatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\challengelogistics.com.au\\national\\FTP\\Home\\")]
        public string NfsUrlString {
            get {
                return ((string)(this["NfsUrlString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vicopensys3168")]
        public string VicSoapPassword {
            get {
                return ((string)(this["VicSoapPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nswopensys2116")]
        public string NswSoapPassword {
            get {
                return ((string)(this["NswSoapPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qldopensys4011")]
        public string QldSoapPassword {
            get {
                return ((string)(this["QldSoapPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("saopensys5033")]
        public string SaSoapPassword {
            get {
                return ((string)(this["SaSoapPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("waopensys6057")]
        public string WaSoapPassword {
            get {
                return ((string)(this["WaSoapPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("opensys1")]
        public string SoapPassword {
            get {
                return ((string)(this["SoapPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://edi.capitaltransport.com.au/soap-services/soap-booker.cgi")]
        public string VicWebServiceEndpoints {
            get {
                return ((string)(this["VicWebServiceEndpoints"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://capsyd-bookings.internetcouriers.com.au/soap-services/soap-booker.cgi")]
        public string NswWebServiceEndpoints {
            get {
                return ((string)(this["NswWebServiceEndpoints"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bne-bookings.internetcouriers.com.au/soap-services/soap-booker.cgi")]
        public string QldWebServiceEndpoints {
            get {
                return ((string)(this["QldWebServiceEndpoints"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://adl-bookings.internetcouriers.com.au/soap-services/soap-booker.cgi")]
        public string SaWebServiceEndpoints {
            get {
                return ((string)(this["SaWebServiceEndpoints"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wa-bookings.internetcouriers.com.au/soap-services/soap-booker.cgi")]
        public string WaWebServiceEndpoints {
            get {
                return ((string)(this["WaWebServiceEndpoints"]));
            }
        }
    }
}
